CREATE VIEW dbo.vw_SampleQuery2
AS
SELECT 
 t.TABLE_CATALOG
,t.table_name
,t.TABLE_SCHEMA
,c.COLUMN_NAME
,c.ORDINAL_POSITION
,c.IS_NULLABLE
,c.DATA_TYPE
,c.NUMERIC_PRECISION
,(c.NUMERIC_PRECISION * c.ORDINAL_POSITION) AS Some_calucation_for_Size
FROM
MASTER.[INFORMATION_SCHEMA].[COLUMNS] AS c
JOIN MASTER.[INFORMATION_SCHEMA].[TABLES] AS t
ON t.TABLE_NAME = c.TABLE_NAME
AND t.TABLE_SCHEMA = c.TABLE_SCHEMA
AND t.TABLE_CATALOG = c.TABLE_CATALOG
WHERE
c.DATA_TYPE IN ('int','smallint','bigint','tinyint')
AND c.ORDINAL_POSITION <= 10 ;
GO